version: "3.9"
   
services:
  db:
    image: postgres
    env_file:
      - .env
  web:
    build: .
    command: python b_test_task/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

