version: "3.3"
   
services:
  db:
    image: postgres
    env_file:
      - .env
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 b_test_task.wsgi:application
    volumes:
      - .:/app
      - ./static:/app/b_test_task/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

